
package service.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MessageService", targetNamespace = "http://endpoint.service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MessageService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMessage", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetMessage")
    @ResponseWrapper(localName = "getMessageResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetMessageResponse")
    @Action(input = "http://endpoint.service/MessageService/getMessageRequest", output = "http://endpoint.service/MessageService/getMessageResponse")
    public String getMessage();

}
